return {
  [463856568047] = {
    ["ChatData"] = {
      ["data"] = {
        [6] = {
          [463856568224] = {
            [1] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Sex"] = 1,
                ["HeadFrameId"] = 72006,
                ["Bubble"] = 76003,
                ["HeadFrame"] = "txk_06",
              },
              ["status"] = 2,
              ["fromname"] = "windy03",
              ["idx"] = 1,
              ["ChatIdx"] = 1,
              ["message"] = "请加入albert的队伍",
              ["fromid"] = 463856568224,
              ["source"] = 0,
              ["time"] = 1540954058.0,
            },
          },
        },
      },
    },
  },
  [463856575009] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856568528] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 135147,
              ["status"] = 1,
              ["fromname"] = "华丽穆得",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 135147,
              ["fromid"] = 463856568528.0,
              ["source"] = 0,
              ["time"] = 1537944968.0,
            },
          },
        },
      },
    },
  },
  [463856575026] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856574261] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 135041,
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 135041,
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346256.0,
            },
          },
        },
        [6] = {
          [463856574261] = {
            [1] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 1,
              ["ChatIdx"] = 1,
              ["message"] = "渣渣",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346273.0,
            },
            [2] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 2,
              ["ChatIdx"] = 1,
              ["message"] = "沼渣",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346282.0,
            },
            [3] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 3,
              ["ChatIdx"] = 1,
              ["message"] = "渣画质",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346293.0,
            },
            [4] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 4,
              ["ChatIdx"] = 1,
              ["message"] = "asa",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346311.0,
            },
            [5] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 5,
              ["ChatIdx"] = 1,
              ["message"] = "1111111",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346325.0,
            },
            [6] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 6,
              ["ChatIdx"] = 1,
              ["message"] = "1166",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346332.0,
            },
            [7] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 7,
              ["ChatIdx"] = 1,
              ["message"] = "1111",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346339.0,
            },
            [8] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 8,
              ["ChatIdx"] = 1,
              ["message"] = "111123243",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346353.0,
            },
            [9] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "王者海棠",
              ["idx"] = 9,
              ["ChatIdx"] = 1,
              ["message"] = "32325",
              ["fromid"] = 463856574261.0,
              ["source"] = 0,
              ["time"] = 1537346370.0,
            },
          },
        },
      },
    },
  },
  [463856572646] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856568048] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 134571,
              ["status"] = 2,
              ["fromname"] = "欧阳朱莉娅",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 134571,
              ["fromid"] = 463856568048.0,
              ["source"] = 0,
              ["time"] = 1536120013.0,
            },
          },
          [463856574738] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 134970,
              ["status"] = 2,
              ["fromname"] = "纳兰克莱儿",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 134970,
              ["fromid"] = 463856574738.0,
              ["source"] = 0,
              ["time"] = 1537153324.0,
            },
          },
          [463856574140] = {
            [2] = {
              ["channel"] = 8,
              ["id"] = 139397,
              ["status"] = 1,
              ["fromname"] = "笑傲小煜",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 2,
              ["ChatIdx"] = 0,
              ["MailId"] = 139397,
              ["fromid"] = 463856574140.0,
              ["source"] = 0,
              ["time"] = 1539760861.0,
            },
            [1] = {
              ["channel"] = 8,
              ["id"] = 139397,
              ["status"] = 1,
              ["fromname"] = "笑傲小煜",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 139397,
              ["fromid"] = 463856574140.0,
              ["source"] = 0,
              ["time"] = 1539760861.0,
            },
          },
          [463856575130] = {
            [2] = {
              ["channel"] = 8,
              ["id"] = 150565,
              ["status"] = 1,
              ["fromname"] = "优雅费滋",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 2,
              ["ChatIdx"] = 0,
              ["MailId"] = 150565,
              ["fromid"] = 463856575130.0,
              ["source"] = 0,
              ["time"] = 1540286144.0,
            },
            [1] = {
              ["channel"] = 8,
              ["id"] = 150565,
              ["status"] = 1,
              ["fromname"] = "优雅费滋",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 150565,
              ["fromid"] = 463856575130.0,
              ["source"] = 0,
              ["time"] = 1540286144.0,
            },
          },
          [463856573559] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 135113,
              ["status"] = 1,
              ["fromname"] = "安晓林",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 135113,
              ["fromid"] = 463856573559.0,
              ["source"] = 0,
              ["time"] = 1537842704.0,
            },
            [2] = {
              ["channel"] = 8,
              ["id"] = 174940,
              ["status"] = 1,
              ["fromname"] = "安晓林",
              ["idx"] = 2,
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["ChatIdx"] = 0,
              ["MailId"] = 174940,
              ["fromid"] = 463856573559.0,
              ["source"] = 0,
              ["time"] = 1541056626.0,
            },
          },
        },
        [6] = {
          [463856568048] = {
            [1] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 72001,
                ["Sex"] = 1,
                ["HeadFrame"] = "txk_01",
              },
              ["status"] = 2,
              ["fromname"] = "欧阳朱莉娅",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["message"] = "快来协助我完成历练笔记任务：击败8次沫小琪<color=#3aa400>[-3#<color=#3aa400>我来协助！</color>]</color>",
              ["fromid"] = 463856568048.0,
              ["source"] = 0,
              ["time"] = 1536120193.0,
            },
            [2] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 72001,
                ["Sex"] = 1,
                ["HeadFrame"] = "txk_01",
              },
              ["status"] = 2,
              ["fromname"] = "欧阳朱莉娅",
              ["idx"] = 2,
              ["ChatIdx"] = 0,
              ["message"] = "快来协助我完成历练笔记任务：击败8次沫小琪<color=#3aa400>[-3#<color=#3aa400>我来协助！</color>]</color>",
              ["fromid"] = 463856568048.0,
              ["source"] = 0,
              ["time"] = 1536120443.0,
            },
            [3] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 72001,
                ["Sex"] = 1,
                ["HeadFrame"] = "txk_01",
              },
              ["status"] = 2,
              ["fromname"] = "欧阳朱莉娅",
              ["idx"] = 3,
              ["ChatIdx"] = 0,
              ["message"] = "快来协助我完成历练笔记任务：击败8次沫小琪<color=#3aa400>[-3#<color=#3aa400>我来协助！</color>]</color>",
              ["fromid"] = 463856568048.0,
              ["source"] = 0,
              ["time"] = 1536120886.0,
            },
            [4] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 72001,
                ["Sex"] = 1,
                ["HeadFrame"] = "txk_01",
              },
              ["status"] = 2,
              ["fromname"] = "欧阳朱莉娅",
              ["idx"] = 4,
              ["ChatIdx"] = 0,
              ["message"] = "快来协助我完成历练笔记任务：击败8次沫小琪<color=#3aa400>[-3#<color=#3aa400>我来协助！</color>]</color>",
              ["fromid"] = 463856568048.0,
              ["source"] = 0,
              ["time"] = 1536121059.0,
            },
            [5] = {
              ["channel"] = 6,
              ["status"] = 1,
              ["fromname"] = "欧阳朱莉娅",
              ["idx"] = 5,
              ["ChatIdx"] = 0,
              ["message"] = "快来协助我完成历练笔记任务：用光系伙伴击败10次黑虎<color=#3aa400>[-3#<color=#3aa400>我来协助！</color>]</color>",
              ["fromid"] = 463856568048.0,
              ["source"] = 0,
              ["time"] = 1537511409.0,
            },
          },
          [463856574738] = {
            [2] = {
              ["channel"] = 6,
              ["status"] = 1,
              ["fromname"] = "纳兰克莱儿",
              ["idx"] = 2,
              ["ChatIdx"] = 0,
              ["message"] = "快来协助我完成历练笔记任务：用火系伙伴击败10次石心子<color=#3aa400>[-3#<color=#3aa400>我来协助！</color>]</color>",
              ["fromid"] = 463856574738.0,
              ["source"] = 0,
              ["time"] = 1537153704.0,
            },
            [1] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Bubble"] = 0,
                ["HeadFrameId"] = 0,
                ["Sex"] = 1,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "纳兰克莱儿",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["message"] = "1111111111111111",
              ["fromid"] = 463856574738.0,
              ["source"] = 0,
              ["time"] = 1537153587.0,
            },
          },
          [463856575100] = {
            [4] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Sex"] = 0,
                ["HeadFrameId"] = 0,
                ["Bubble"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "大爱波比",
              ["idx"] = 4,
              ["ChatIdx"] = 1,
              ["message"] = "[#18]",
              ["fromid"] = 463856575100,
              ["source"] = 0,
              ["time"] = 1540793953.0,
            },
            [1] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Sex"] = 0,
                ["HeadFrameId"] = 0,
                ["Bubble"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "大爱波比",
              ["idx"] = 1,
              ["ChatIdx"] = 1,
              ["message"] = "6666",
              ["fromid"] = 463856575100,
              ["source"] = 0,
              ["time"] = 1540793946.0,
            },
            [2] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Sex"] = 0,
                ["HeadFrameId"] = 0,
                ["Bubble"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "大爱波比",
              ["idx"] = 2,
              ["ChatIdx"] = 1,
              ["message"] = "[#17]",
              ["fromid"] = 463856575100,
              ["source"] = 0,
              ["time"] = 1540793949.0,
            },
            [3] = {
              ["channel"] = 6,
              ["PlayerData"] = {
                ["Sex"] = 0,
                ["HeadFrameId"] = 0,
                ["Bubble"] = 0,
                ["HeadFrame"] = "",
              },
              ["status"] = 2,
              ["fromname"] = "大爱波比",
              ["idx"] = 3,
              ["ChatIdx"] = 1,
              ["message"] = "[#17]",
              ["fromid"] = 463856575100,
              ["source"] = 0,
              ["time"] = 1540793952.0,
            },
          },
        },
      },
    },
  },
  [463856573738] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856575109] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 148959,
              ["status"] = 1,
              ["fromname"] = "kim0298",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 148959,
              ["fromid"] = 463856575109.0,
              ["source"] = 0,
              ["time"] = 1540213322.0,
            },
          },
        },
      },
    },
  },
  [463856573005] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856573646] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 135414,
              ["status"] = 1,
              ["fromname"] = "嘉利德博拉",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 135414,
              ["fromid"] = 463856573646.0,
              ["source"] = 0,
              ["time"] = 1539311059.0,
            },
          },
        },
      },
    },
  },
  [463856574734] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856575244] = {
            [1] = {
              ["channel"] = 8,
              ["id"] = 171828,
              ["status"] = 1,
              ["fromname"] = "笑傲泡泡",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 171828,
              ["fromid"] = 463856575244.0,
              ["source"] = 0,
              ["time"] = 1540983588.0,
            },
          },
        },
      },
    },
  },
  [463856574239] = {
    ["ChatData"] = {
      ["data"] = {
        [8] = {
          [463856574612] = {
            [2] = {
              ["channel"] = 8,
              ["id"] = 134408,
              ["status"] = 1,
              ["fromname"] = "旋律鸣人",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 2,
              ["ChatIdx"] = 0,
              ["MailId"] = 134408,
              ["fromid"] = 463856574612.0,
              ["source"] = 0,
              ["time"] = 1535687421.0,
            },
            [1] = {
              ["channel"] = 8,
              ["id"] = 134408,
              ["status"] = 1,
              ["fromname"] = "旋律鸣人",
              ["message"] = "我添加你为好友了，一起来聊天吧~",
              ["idx"] = 1,
              ["ChatIdx"] = 0,
              ["MailId"] = 134408,
              ["fromid"] = 463856574612.0,
              ["source"] = 0,
              ["time"] = 1535687421.0,
            },
          },
        },
      },
    },
  },
}